"""indices en cotizaciones y proyectos

Revision ID: 12584b585a23
Revises: 72df8a4cf0ac
Create Date: 2026-07-30 12:57:08.801682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12584b585a23'
down_revision = '72df8a4cf0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotizaciones_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index('ix_cotizaciones_estado_creado_en', ['estado', 'creado_en'], unique=False)

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.create_index('ix_proyectos_trabajador_estado', ['trabajador_id', 'estado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_index('ix_proyectos_trabajador_estado')

    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.drop_index('ix_cotizaciones_estado_creado_en')
        batch_op.drop_index(batch_op.f('ix_cotizaciones_cliente_id'))

    # ### end Alembic commands ###
