"""aceptacion, pagos, fotos de avance y bitacora

Revision ID: 22813a210cc2
Revises: 39b12a41b3bf
Create Date: 2026-07-30 15:32:20.334169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22813a210cc2'
down_revision = '39b12a41b3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('entidad', sa.String(length=40), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('antes', sa.JSON(), nullable=True),
    sa.Column('despues', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.create_index('ix_bitacora_entidad', ['entidad', 'entidad_id'], unique=False)

    op.create_table('fotos_avance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('subida_por_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['subida_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fotos_avance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotos_avance_proyecto_id'), ['proyecto_id'], unique=False)

    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo', sa.String(length=30), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('comprobante_url', sa.String(length=300), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_proyecto_id'), ['proyecto_id'], unique=False)

    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aceptada_en', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aceptada_ip', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.drop_column('aceptada_ip')
        batch_op.drop_column('aceptada_en')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_proyecto_id'))

    op.drop_table('pagos')
    with op.batch_alter_table('fotos_avance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotos_avance_proyecto_id'))

    op.drop_table('fotos_avance')
    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.drop_index('ix_bitacora_entidad')

    op.drop_table('bitacora')
    # ### end Alembic commands ###
