"""tipos_trabajo y spec en cotizaciones

Revision ID: 2e198755a97e
Revises: 12584b585a23
Create Date: 2026-07-30 13:10:18.932337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e198755a97e'
down_revision = '12584b585a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('sistema', sa.String(length=20), nullable=False),
    sa.Column('unidad', sa.String(length=4), nullable=False),
    sa.Column('altura_referencia_m', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('modo_dibujo', sa.String(length=20), nullable=False),
    sa.Column('admite_barrotes', sa.Boolean(), nullable=True),
    sa.Column('minimo_facturable', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spec', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.drop_column('spec')

    op.drop_table('tipos_trabajo')
    # ### end Alembic commands ###
