"""partidas y cotizaciones con folio/vigencia/totales

Revision ID: 39b12a41b3bf
Revises: fcd82944eeeb
Create Date: 2026-07-30 14:08:43.522382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b12a41b3bf'
down_revision = 'fcd82944eeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('tipo_trabajo_id', sa.Integer(), nullable=True),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desglose', sa.JSON(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['tipo_trabajo_id'], ['tipos_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partidas_cotizacion_id'), ['cotizacion_id'], unique=False)

    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folio', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vigencia_hasta', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tarifa_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_cotizaciones_folio', ['folio'])
        batch_op.create_foreign_key('fk_cotizaciones_tarifa_id', 'tarifas', ['tarifa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cotizaciones_tarifa_id', type_='foreignkey')
        batch_op.drop_constraint('uq_cotizaciones_folio', type_='unique')
        batch_op.drop_column('tarifa_id')
        batch_op.drop_column('total')
        batch_op.drop_column('iva')
        batch_op.drop_column('descuento')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('vigencia_hasta')
        batch_op.drop_column('folio')

    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partidas_cotizacion_id'))

    op.drop_table('partidas')
    # ### end Alembic commands ###
