"""esquema inicial

Revision ID: 44994b7374c2
Revises: 
Create Date: 2026-07-30 12:11:32.450296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44994b7374c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precios_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=20), nullable=False),
    sa.Column('precio_base_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_acabado_extra_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('material', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_referencia_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagen_url', sa.String(length=300), nullable=True),
    sa.Column('destacado', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('material', sa.String(length=20), nullable=False),
    sa.Column('ancho_m', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('alto_m', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('con_acabado', sa.Boolean(), nullable=True),
    sa.Column('metros_cuadrados', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('precio_estimado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('avance_porcentaje', sa.Integer(), nullable=True),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.Column('fecha_estimada_entrega', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proyectos')
    op.drop_table('cotizaciones')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('precios_material')
    # ### end Alembic commands ###
