"""agregar token_version a usuarios

Revision ID: 72df8a4cf0ac
Revises: 44994b7374c2
Create Date: 2026-07-30 12:38:04.622661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72df8a4cf0ac'
down_revision = '44994b7374c2'
branch_labels = None
depends_on = None


def upgrade():
    # server_default='0' es necesario aquí: la tabla usuarios en producción ya
    # tiene filas, y agregar una columna NOT NULL sin default hace que Postgres
    # rechace la migración por violar la restricción en las filas existentes.
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    # ### end Alembic commands ###
