"""costo real y registro de horas

Revision ID: a117ab36023e
Revises: 22813a210cc2
Create Date: 2026-07-30 15:46:36.611149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a117ab36023e'
down_revision = '22813a210cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_horas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('horas', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('notas', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_horas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_horas_proyecto_id'), ['proyecto_id'], unique=False)

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_material_real', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_column('costo_material_real')

    with op.batch_alter_table('registro_horas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_horas_proyecto_id'))

    op.drop_table('registro_horas')
    # ### end Alembic commands ###
