"""tarifas versionadas

Revision ID: fcd82944eeeb
Revises: 2e198755a97e
Create Date: 2026-07-30 13:37:26.153441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd82944eeeb'
down_revision = '2e198755a97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarifas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('creada_por_id', sa.Integer(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precios_tarifa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarifa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_trabajo_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=40), nullable=False),
    sa.Column('clave', sa.String(length=40), nullable=False),
    sa.Column('unidad', sa.String(length=6), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tarifa_id'], ['tarifas.id'], ),
    sa.ForeignKeyConstraint(['tipo_trabajo_id'], ['tipos_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('precios_tarifa', schema=None) as batch_op:
        batch_op.create_index('ix_precios_tarifa_tarifa_id', ['tarifa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precios_tarifa', schema=None) as batch_op:
        batch_op.drop_index('ix_precios_tarifa_tarifa_id')

    op.drop_table('precios_tarifa')
    op.drop_table('tarifas')
    # ### end Alembic commands ###
